package latte.Absyn; // Java Package generated by the BNF Converter.

public class AVar extends Expr {
  public final ArrayE arraye_;
  public AVar(ArrayE p1) { arraye_ = p1; }

  public <R,A> R accept(latte.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.AVar) {
      latte.Absyn.AVar x = (latte.Absyn.AVar)o;
      return this.arraye_.equals(x.arraye_);
    }
    return false;
  }

  public int hashCode() {
    return this.arraye_.hashCode();
  }


}
