package latte.Absyn; // Java Package generated by the BNF Converter.

public class ClInh extends TopDef {
  public final String ident_1, ident_2;
  public final ListClassElt listclasselt_;
  public ClInh(String p1, String p2, ListClassElt p3) { ident_1 = p1; ident_2 = p2; listclasselt_ = p3; }

  public <R,A> R accept(latte.Absyn.TopDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.ClInh) {
      latte.Absyn.ClInh x = (latte.Absyn.ClInh)o;
      return this.ident_1.equals(x.ident_1) && this.ident_2.equals(x.ident_2) && this.listclasselt_.equals(x.listclasselt_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_1.hashCode())+this.ident_2.hashCode())+this.listclasselt_.hashCode();
  }


}
