package latte.Absyn; // Java Package generated by the BNF Converter.

public class FldAccess extends FieldE {
  public final Expr expr_;
  public final String ident_;
  public FldAccess(Expr p1, String p2) { expr_ = p1; ident_ = p2; }

  public <R,A> R accept(latte.Absyn.FieldE.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.FldAccess) {
      latte.Absyn.FldAccess x = (latte.Absyn.FldAccess)o;
      return this.expr_.equals(x.expr_) && this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expr_.hashCode())+this.ident_.hashCode();
  }


}
