package latte.Absyn; // Java Package generated by the BNF Converter.

public class ProgramCons extends Program {
  public final ListTopDef listtopdef_;
  public ProgramCons(ListTopDef p1) { listtopdef_ = p1; }

  public <R,A> R accept(latte.Absyn.Program.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.ProgramCons) {
      latte.Absyn.ProgramCons x = (latte.Absyn.ProgramCons)o;
      return this.listtopdef_.equals(x.listtopdef_);
    }
    return false;
  }

  public int hashCode() {
    return this.listtopdef_.hashCode();
  }


}
