package instant.Absyn; // Java Package generated by the BNF Converter.

public abstract class Exp implements java.io.Serializable {
  public abstract <R,A> R accept(Exp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(instant.Absyn.ExpAdd p, A arg);
    public R visit(instant.Absyn.ExpSub p, A arg);
    public R visit(instant.Absyn.ExpMul p, A arg);
    public R visit(instant.Absyn.ExpDiv p, A arg);
    public R visit(instant.Absyn.ExpLit p, A arg);
    public R visit(instant.Absyn.ExpVar p, A arg);

  }

}
