package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class ArrayE implements java.io.Serializable {
  public abstract <R,A> R accept(ArrayE.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(latte.Absyn.ArrAccess p, A arg);

  }

}
