package latte.Absyn; // Java Package generated by the BNF Converter.

public class AssArr extends Stmt {
  public final ArrayE arraye_;
  public final Expr expr_;
  public AssArr(ArrayE p1, Expr p2) { arraye_ = p1; expr_ = p2; }

  public <R,A> R accept(latte.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.AssArr) {
      latte.Absyn.AssArr x = (latte.Absyn.AssArr)o;
      return this.arraye_.equals(x.arraye_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.arraye_.hashCode())+this.expr_.hashCode();
  }


}
