package latte.Absyn; // Java Package generated by the BNF Converter.

public class AssFie extends Stmt {
  public final FieldE fielde_;
  public final Expr expr_;
  public AssFie(FieldE p1, Expr p2) { fielde_ = p1; expr_ = p2; }

  public <R,A> R accept(latte.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.AssFie) {
      latte.Absyn.AssFie x = (latte.Absyn.AssFie)o;
      return this.fielde_.equals(x.fielde_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.fielde_.hashCode())+this.expr_.hashCode();
  }


}
