package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class ClassElt implements java.io.Serializable {
  public abstract <R,A> R accept(ClassElt.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(latte.Absyn.Field p, A arg);
    public R visit(latte.Absyn.Method p, A arg);

  }

}
