package latte.Absyn; // Java Package generated by the BNF Converter.

public class ClDef extends TopDef {
  public final String ident_;
  public final ListClassElt listclasselt_;
  public ClDef(String p1, ListClassElt p2) { ident_ = p1; listclasselt_ = p2; }

  public <R,A> R accept(latte.Absyn.TopDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.ClDef) {
      latte.Absyn.ClDef x = (latte.Absyn.ClDef)o;
      return this.ident_.equals(x.ident_) && this.listclasselt_.equals(x.listclasselt_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.listclasselt_.hashCode();
  }


}
