package latte.Absyn; // Java Package generated by the BNF Converter.

public class EArrayCons extends Expr {
  public final Type type_;
  public final Integer integer_;
  public EArrayCons(Type p1, Integer p2) { type_ = p1; integer_ = p2; }

  public <R,A> R accept(latte.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.EArrayCons) {
      latte.Absyn.EArrayCons x = (latte.Absyn.EArrayCons)o;
      return this.type_.equals(x.type_) && this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_.hashCode())+this.integer_.hashCode();
  }


}
