package latte.Absyn; // Java Package generated by the BNF Converter.

public class EClassCons extends Expr {
  public final Type type_;
  public EClassCons(Type p1) { type_ = p1; }

  public <R,A> R accept(latte.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.EClassCons) {
      latte.Absyn.EClassCons x = (latte.Absyn.EClassCons)o;
      return this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return this.type_.hashCode();
  }


}
