package latte.Absyn; // Java Package generated by the BNF Converter.

public class For extends Stmt {
  public final Stmt stmt_1, stmt_2, stmt_3;
  public final Expr expr_;
  public For(Stmt p1, Expr p2, Stmt p3, Stmt p4) { stmt_1 = p1; expr_ = p2; stmt_2 = p3; stmt_3 = p4; }

  public <R,A> R accept(latte.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.For) {
      latte.Absyn.For x = (latte.Absyn.For)o;
      return this.stmt_1.equals(x.stmt_1) && this.expr_.equals(x.expr_) && this.stmt_2.equals(x.stmt_2) && this.stmt_3.equals(x.stmt_3);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.stmt_1.hashCode())+this.expr_.hashCode())+this.stmt_2.hashCode())+this.stmt_3.hashCode();
  }


}
