package instant.Absyn; // Java Package generated by the BNF Converter.

public class ExpLit extends Exp {
  public final Integer integer_;
  public ExpLit(Integer p1) { integer_ = p1; }

  public <R,A> R accept(instant.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof instant.Absyn.ExpLit) {
      instant.Absyn.ExpLit x = (instant.Absyn.ExpLit)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
