package instant.Absyn; // Java Package generated by the BNF Converter.

public class Prog extends Program {
  public final ListStmt liststmt_;
  public Prog(ListStmt p1) { liststmt_ = p1; }

  public <R,A> R accept(instant.Absyn.Program.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof instant.Absyn.Prog) {
      instant.Absyn.Prog x = (instant.Absyn.Prog)o;
      return this.liststmt_.equals(x.liststmt_);
    }
    return false;
  }

  public int hashCode() {
    return this.liststmt_.hashCode();
  }


}
