package instant.Absyn; // Java Package generated by the BNF Converter.

public class SExp extends Stmt {
  public final Exp exp_;
  public SExp(Exp p1) { exp_ = p1; }

  public <R,A> R accept(instant.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof instant.Absyn.SExp) {
      instant.Absyn.SExp x = (instant.Absyn.SExp)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
